### PR TITLE
Fix dashboard

### LINKED ISSUE #375: Dashboard error
As @cracraft reminded me, the JWQL dashboard page is throwing an error again.

It looks like there is a new directory in the `outputs` directory that it doesn't know how to handle: `miri_total_file_count_by_type`.

We should probably make the `get_dashboard_components()` function more robust to these kinds of problems.

### PR DESCRIPTION
**Pull request by laurenmarietta**
Closes #375.

This PR fixes the bug where the dashboard page does not load, throwing an error.

I got around it by adding checks in `data_containers/get_dashboard_components()` to only attempt to load HTML/JavaScript files from known monitors. I also added a feature to programmatically generate formatted plot names from the component files.

This means that a developer adding a new monitor to the dashboard page will need to explicitly add the monitor to `name_dict` in `data_containers/get_dashboard_components()` for it to be loaded. However, once a monitor is added to that dictionary, every plot in the output directory for that monitor will be shown.

### CODE REVIEW

**Comment by cracraft** [comment]
Is there a way to view the finished results, or do I just have to read code?

**Comment by bourque** [comment]
@cracraft I think you should be able to see it in action by running the web app locally:

```
cd jwql/jwql/website/
python manage.py runserver
```
then visit `http://127.0.0.1:8000/` in a browser.

**Comment by laurenmarietta** [comment]
You would have to switch into this branch first, though. This should do it:
```
git checkout -b laurenmarietta-fix-dashboard develop
git pull https://github.com/laurenmarietta/jwql.git fix-dashboard
```

**Comment by cracraft** [comment]
Thanks for the instructions. The plots are displaying now, but we've got some odd behavior, and I don't know if that goes in this ticket or not. Some plots show a long history of queries (many dates in the plots) and others show only single points. Would that have happened as part of this update?

**Comment by bourque** [comment]
@cracraft It could be that some of the plots only have a single point because the filesystem monitor hasn't been running every day; I can look into that.  The fact that plots are rendering should indicate that this PR is correctly fixing the issue at hand though.

**Comment by cracraft** [comment]
While the plots haven't been running every day, they have been tested before, so I assumed the data would still be there. (unless part of the database got reset?)

**Comment by bourque** [comment]
@cracraft Yeah, since the database schema was overhauled in #328, the database had to be reset

**Comment by cracraft** [comment]
Ok, then I'd say that since I can now see the plots in this branch, it fixes the problem.

**Comment by bourque** [comment]
Thanks @laurenmarietta, this looks good and works well on my end.  And it looks like the filesystem monitor plots are now updating with new data points now that #328 is in `master`!

**Pull request merged**
