### PR TITLE
Add new NIRCam anomalies

### LINKED ISSUE #1126: Add new anomaly types for NIRCam
Discussed in the NIRCam meeting today:

Should we add claws and wisps to the list of NIRCam anomalies? 
@bsunnquist is the best one to make the call on this.

We should also add a "scattered light" entry, to capture exposures with unexpected scattered light features.

### PR DESCRIPTION
**Pull request by bhilbert4**
Resolves #1126 

Adds a few new NIRCam anomalies to the list. Note: new columns will need to be added to the anomaly database.

### CODE REVIEW

**Comment by bhilbert4** [comment]
Looks like columns need to be added to the database before the updated page can be viewed on the test server.

**Comment by bhilbert4** [comment]
@mfixstsci this is ready for review. I should probably learn how to add columns to the database table at some point.

**Comment by bhilbert4** [comment]
Tests are failing because the MAST server is not available. Maybe I'll wait a bit and try again later.

**Review by mfixstsci — APPROVED** [review]
Thanks @bhilbert4 one question, are these values now reflected in the web app and the in the database? Have you tested this yet?

**Comment by bhilbert4** [comment]
I tried checking on the test server this morning, but it turns out that the page can't be built until the new columns are added to the database. Until that happens, the exposure page crashes. I don't know yet how to add columns to the database. So we should probably add those columns to all of the databases and have a quick look on the dev or test servers before merging this. Also, #1133 adds some anomalies for NIRISS, so maybe it makes sense to add all the columns together. I'm happy to learn how to add columns to the database.

**Comment by mfixstsci** [comment]
@bhilbert4 I just completely ignored this process for NIRISS (better or worse) and then just added the columns to production post merge 😭 Looks like there are some conflicts now if you could resolve them. Let me know what you'd prefer to do. I can update test if you'd like before we merge it.

**Comment by bhilbert4** [comment]
@mfixstsci I knew that conflict would pop up depending on whether the niriss or nircam PR was merged first. Anyway, it's fixed.

**Comment by bhilbert4** [comment]
I'm happy to look at it on test if you'd like. I'm pretty confident everything will be ok though (he said, just before the holiday break starts)

**Comment by mfixstsci** [comment]
@bhilbert4 thanks for addressing that, I will take a look when the tests pass and just add the columns by hand. I've already done it once today, so why not twice?

**Comment by bhilbert4** [comment]
Practice makes perfect, right? 😄

**Review by mfixstsci — APPROVED** [review]
LGTM

**Pull request merged**
