### PR TITLE
Added documentation button to instrument pages

### PR DESCRIPTION
**Pull request by catherine-martlin**
See issue #148 

I may need to change the link used for FGS - where is the specific documentation for that kept?

### CODE REVIEW

**Comment by catherine-martlin** [comment]
Also, I made the link the same for all the instruments - the html links aren't a useful pattern so if we wanted to send people straight to that instrument documentation we would have to create either a set of conditions or a list somewhere for the template to know where to send people. It's a bit easier to just link all to the landing page where the information for each instrument is obvious (except FGS - were do I find that documentation?)

**Comment by laurenmarietta** [comment]
Here is the JDox page for FGS - such a black sheep! https://jwst-docs.stsci.edu/display/JTI/Fine+Guidance+Sensor%2C+FGS?q=fgs

If only because FGS is different, it might be a good idea to do like you mentioned and pass the specific URLs for each instrument into the pages. I imagine the best way to go about doing this would be to add a `doc_url` key (or something like it) to the `context` dictionary that is passed out in `views.instrument()`. Something like this maybe:

```python
url_dict = {
    'fgs': 'https://jwst-docs.stsci.edu/display/JTI/Fine+Guidance+Sensor%2C+FGS?q=fgs',
    'miri': 'https://jwst-docs.stsci.edu/display/JTI/Mid-Infrared+Instrument%2C+MIRI',
    ...
}
doc_url = url_dict[inst]
context = {
    'doc_url': doc_url, 
    ...
}
```

Thoughts?

**Comment by catherine-martlin** [comment]
That seems like the perfect way to do that - I'll give it a try and let you know if I have any questions.

**Comment by catherine-martlin** [comment]
@laurenmarietta @bourque - I've updated the views.py and the instrument.html to allow for individual document links to the JDOCs for each instrument. Let me know if we want to change the format or add any specific pngs to pages on our web pages! I'm happy to do more additions if we can think of any good ones.

**Pull request merged**
