### PR TITLE
Fix failing dark monitor

### LINKED ISSUE #1223: Dark monitor page failing to load
The dark monitor page for all instruments currently crashes with the traceback: 

name 'xdim' is not defined
monitor_dark_bokeh.py, line 241, in create_plot

### PR DESCRIPTION
**Pull request by bhilbert4**
Resolves #1223 
Adds missing definition of xdim, ydim.

### CODE REVIEW

**Comment by bhilbert4** [comment]
Checking on the test server, this seems to solve the problem.

**Comment by bhilbert4** [comment]
@mfixstsci this is ready for review. We should get this in before the meeting on Wednesday.

**Review by mfixstsci — APPROVED** [review]
Looks good to me!

**Comment by mfixstsci** [comment]
> @mfixstsci this is ready for review. We should get this in before the meeting on Wednesday.

Sorry for the late reply @bhilbert4 I just bypassed showing the dark monitor.

**Comment by mfixstsci** [comment]
@bhilbert4 Just tested this out on `dev` and it looks great!

**Pull request merged**
