### PR TITLE
Fix bug with pyvo output

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR corrects a bug in the output from pyvo in get_instrument_proposals() that was causing the app to crash.

### CODE REVIEW

**Comment by bhilbert4** [comment]
Would be good to bring this over to the test server and make sure there aren't any other problems. The test server seems to be down at the moment though, so I can try that tomorrow.

**Comment by bhilbert4** [comment]
I just checked this on the test server and it works. @mfixstsci this is ready for review.

**Review by mfixstsci — APPROVED** [review]
Looks good @bhilbert4, just curious, what did the `compressed()` method do to the list? Is this a built-in to `list` objects?

**Comment by bhilbert4** [comment]
compressed() is a method of numpy masked arrays, which is what pyvo returns. Or I should say, it returns an astropy table where the column we are interested in contains a masked array. compressed() just returns all of the non-masked elements of the masked array.

**Comment by bhilbert4** [comment]
I had accidentally been calling compressed() twice before this fix.

**Comment by mfixstsci** [comment]
@bhilbert4 I noticed that it was done twice, I didn't know if there was some clever typecasting going on there. Thanks for the fix!

**Comment by BradleySappington** [comment]
Just tried running JWQL on my machine, got the following issue traceback  (I cant load any thumbnail arrays):

`Traceback (most recent call last):
  File "/Users/bsappington/miniconda3/envs/jwql-3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/bsappington/miniconda3/envs/jwql-3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bsappington/repositories/jwql/jwql/website/apps/jwql/views.py", line 275, in archived_proposals_ajax
    all_proposals = get_instrument_proposals(inst)
  File "/Users/bsappington/repositories/jwql/jwql/website/apps/jwql/data_containers.py", line 797, in get_instrument_proposals
    tap_results = tap_service.search(f"select distinct proposal_id from dbo.ObsPointing where obs_collection='JWST' and calib_level>0 and instrument_name like '{instrument.upper()}%'")
  File "/Users/bsappington/miniconda3/envs/jwql-3.8/lib/python3.8/site-packages/pyvo/dal/tap.py", line 246, in run_sync
    return self.create_query(
  File "/Users/bsappington/miniconda3/envs/jwql-3.8/lib/python3.8/site-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/Users/bsappington/miniconda3/envs/jwql-3.8/lib/python3.8/site-packages/pyvo/dal/query.py", line 245, in execute_votable
    raise DALFormatError(e, self.queryurl)
pyvo.dal.exceptions.DALFormatError: ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
[09/May/2022 12:47:55] "GET /ajax/FGS/archive/ HTTP/1.1" 500 232975`

**Pull request merged**
