### PR TITLE
Use integer for dither_points metadata entry

### LINKED ISSUE #772: Dark Monitor failure due to dither point keyword values in data
**Describe the bug**
The JWST pipeline recently changed the definition of the metadata entry in their datamodels for the number of dithers. Previously the metadata entry: `model.meta.dither.dither_points` mapped to the `NDITHPTS` keyword, and was expected to be a string (e.g. '0'). Starting with jwst version 1.2.1 (I believe), `model.meta.dither.dither_points` now maps to the `NRIMDTPT` keyword, with an expected integer value. 

Data from recent rehearsals predates this change, and so those files contain the NDITHPTS keyword. When one of these files is read in by e.g. one of the instrument monitors, the jwst package will throw a warning. But if the monitor then attempts to write out that data into a new file (e.g. after running a pipeline step) without changing the dither_points metadata to be an integer, then the jwst package will crash.

See the log file for today's run of the dark_monitor for an example.
dark_monitor_2021-07-30-03-30.log

It is a little weird to see this only now. We've had version >=1.2.1 of the pipeline for a while, and the files in the new filesystem for a few weeks....

**To Reproduce**
Run the dark_monitor

**Expected behavior**
Anywhere that a science file is written out, the dither_points metadata should be checked to be sure it's an integer.

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR makes a small change to be sure that the model.meta.dither.dither_points metadata entry for a jwst datamodel is an integer. The definition recently changed from a string to an integer in the jwst package. However, some of the rehearsal data in the filesystem are old enough that they use a string. This change checks the data type of that entry before saving a datamodel to a new file. 

Currently this fix is only in instrument_monitors/pipeline_tools.py. Instrument monitors that use jwst.datamodels to write out new files but don't use pipeline_tools.py may need to implement their own fixes. 

Resolves #772

### CODE REVIEW

**Comment by bhilbert4** [comment]
With the latest commit, I think the dark monitor crashed we'd been seeing should be fixed, and I believe these changes will fix the bad pixel monitor crashes as well. A manual run of the dark monitor is in progress and has gotten beyond where it was crashing. I'll check the logs tomorrow to see how everything went.

**Comment by bhilbert4** [comment]
Latest run on the dev server for all instruments completed successfully! I can see that separate MAST queries are now made for each RAPID-style readout pattern. No crashes means that the readout pattern column was also added to the database tables successfully...I guess?

**Review by bourque — COMMENTED** [review]
Thanks for these changes @bhilbert4!  The code changes look good to me, and very well commented!

I am going to test this out early this week

**Comment by bourque** [comment]
Looks like the dark monitor is working fine. The only potential issue I saw was that the `fgs_dark_pixel_stats` table did not include any results.  Not sure if that is expected or not.

**Comment by bhilbert4** [comment]
Looking at the latest log file, it looks like not enough files were found for any FGS aperture to trigger the dark monitor. There were two apertures where the MAST results indicated enough files were present, but the filesystem search revealed that none of the files were actually present. Given all this, I think an empty FGS dark pixel stats table is expected.

**Comment by bourque** [comment]
It looks like the Bad Pixel Monitor is running into a problem:

```
08/16/2021 15:57:29 PM INFO: Step dark_current running with args (<RampModel(2, 4, 256, 2048) from jw00674012001_03101_00001_nrca1_uncal.fits>,).
08/16/2021 15:57:29 PM INFO: Step dark_current parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': '/internal/data1/outputs/dev/bad_pixel_monitor/data/nircam_nrca1_full', 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'dark_output': None}
08/16/2021 15:57:29 PM INFO: Using DARK reference file /references/jwst/jwst_nircam_dark_0231.fits
08/16/2021 15:57:29 PM DEBUG: No ASDF information found. Cannot skip updating from FITS headers.
08/16/2021 15:57:31 PM INFO: Science data nints=2, ngroups=4, nframes=1, groupgap=0
08/16/2021 15:57:31 PM INFO: Dark data nints=1, ngroups=187, nframes=1, groupgap=0
08/16/2021 15:57:32 PM DEBUG: subtract_dark: nints=2, ngroups=4, size=256,2048
08/16/2021 15:57:32 PM CRITICAL: Traceback (most recent call last):
  File "jwql/jwql/utils/logging_functions.py", line 284, in wrapped
    func(*args, **kwargs)
  File "jwql/jwql/utils/logging_functions.py", line 249, in wrapped
    func(*args, **kwargs)
  File "bad_pixel_monitor.py", line 1055, in run
    self.process(flat_uncal_files, flat_rate_files, dark_uncal_files, dark_rate_files)
  File "bad_pixel_monitor.py", line 814, in process
    ramp_fit=True, save_fitopt=True)
  File "jwql/jwql/instrument_monitors/pipeline_tools.py", line 345, in calwebb_detector1_save_jump
    model.run(datamodel)
  File "miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/jwst/pipeline/calwebb_detector1.py", line 115, in process
    result = self.dark_current(result)
  File "envs/jwql-3.7/lib/python3.7/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/jwst/dark_current/dark_current_step.py", line 54, in process
    input_model, dark_model, dark_output
  File "miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/jwst/dark_current/dark_sub.py", line 94, in do_correction
    output_model = subtract_dark(input_model, dark_model)
  File "miniconda3/envs/jwql-3.7/lib/python3.7/site-packages/jwst/dark_current/dark_sub.py", line 332, in subtract_dark
    output.pixeldq = np.bitwise_or(input.pixeldq, darkdq)
ValueError: operands could not be broadcast together with shapes (256,2048) (2048,2048) 
```

**Comment by bhilbert4** [comment]
Hmm. That's a file with some bad metadata. It claims to be full frame data, but in reality it isn't.

**Comment by bhilbert4** [comment]
I guess I can add in a check on the array size for each file. I don't expect something like this to happen in flight (although I could be wrong).

**Comment by bourque** [comment]
@bhilbert4 That sounds good for now.  It is annoying that it is an issue that we have to deal with now but will likely only be temporary, but i'm not sure what else to do.

Perhaps a few months after operations, we can revisit some or all of these monitors to see how they may be simplified once more homogeneous data are being processed.

**Comment by bhilbert4** [comment]
Hopefully once we start ignoring all rehearsal data this won't be an issue anymore, but it can't hurt to guard against it:
https://jira.stsci.edu/browse/JWSTDMS-594

**Comment by bhilbert4** [comment]
I'm also confused at how the dark monitor didn't fail with the same problem...

**Comment by bourque** [comment]
Ok, to summarize and organize this effort, here is the To-do list before this can be merged:

- [ ] Make sure the `dark_monitor` completes successfully (closes #763 and #772 and #776)
- [ ] Make sure the `bad_pixel_monitor` completes successfully (closes #761)
- [ ] Update the `readnoise_monitor` to handle new ` mast_query_darks()` parameters (#784) (@bsunnquist)
- [ ] Make sure the `readnoise_monitor` completes successfully (closes #784)
- [ ] Final PR review
- [ ] Update branch with `develop`
- [ ] Status checks pass

@bsunnquist To make things easier, would you mind updating this branch directly to solve #784?  Then we can treat this branch as a 'fix-all-monitors' branch.

**Comment by bsunnquist** [comment]
Yeah I can make sure the readnoise monitor is working. @bhilbert4 can confirm, but I believe he made a change to the mast_query_darks function that would solve the readnoise monitor issue (allowing it to work if no readpattern is specified), but let me know if not and I can add that change to that function.

**Comment by bourque** [comment]
Thanks @bsunnquist, I think the Readnoise Monitor is crashing in this branch still, I just tried it: `logs/dev/readnoise_monitor/readnoise_monitor_2021-08-24-10-59.log`

```
TypeError: mast_query_darks() missing 1 required positional argument: 'end_date'
```

**Comment by bourque** [comment]
The dark monitor ran successfully 👍

**Comment by bourque** [comment]
The `bad_pixel_monitor` however is crashing:

```
08/24/2021 12:00:32 PM INFO: Working on aperture FGS1_FULL in fgs
08/24/2021 12:00:32 PM INFO: 	No query history for FGS1_FULL. Beginning search date will be set to 57357.0.
08/24/2021 12:00:32 PM INFO: 	No query history for FGS1_FULL. Beginning search date will be set to 57357.0.
08/24/2021 12:00:32 PM INFO: 	Flat field query times: 57357.0 59450.667041903915
08/24/2021 12:00:32 PM INFO: 	Dark current query times: 57357.0 59450.667041903915
08/24/2021 12:00:33 PM CRITICAL: Traceback (most recent call last):
  File "/envs/jwql-3.7/lib/python3.7/site-packages/stdatamodels/properties.py", line 287, in __getattr__
    val = self._instance[attr]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/jwql/jwql/utils/logging_functions.py", line 284, in wrapped
    func(*args, **kwargs)
  File "/jwql/jwql/utils/logging_functions.py", line 249, in wrapped
    func(*args, **kwargs)
  File "bad_pixel_monitor.py", line 1026, in run
    apcheck_flat_entries = pipeline_tools.aperture_size_check(new_flat_entries, instrument, aperture)
  File "/jwql/jwql/instrument_monitors/pipeline_tools.py", line 106, in aperture_size_check
    array_size_y, array_size_x = model.data.shape[-2:]
  File "/envs/jwql-3.7/lib/python3.7/site-packages/stdatamodels/properties.py", line 290, in __getattr__
    raise AttributeError("No attribute '{0}'".format(attr))
AttributeError: No attribute 'data'

08/24/2021 12:00:33 PM CRITICAL: CRASHED
```

@bsunnquist @bhilbert4 Any idea what might be going on here?

**Comment by bhilbert4** [comment]
Interesting. A file that has no data in it? Not even an empty data array, but no data attribute at all?

**Review by bourque — COMMENTED** [review]
I have reviewed the code changes here and they look great!  And extremely well documented.  Thanks @bhilbert4!

**Comment by bsunnquist** [comment]
Yes thanks Bryan - the changes look good for the Readnoise Monitor and the latest dev logs all look good as well.

**Comment by bourque** [comment]
@bhilbert4 Thanks again for all of your hard work on this one, it was a doozie!

**Pull request merged**
