### PR TITLE
Anomaly naming

### PR DESCRIPTION
**Pull request by BradleySappington**
NIRSPEC Only:
 Guidestar Failure -> (remove)
 Crosstalk -> (remove)
 Data Transfer Error -> (remove)
 (add) -> Transient Short
 (add) -> Subsequently Masked Short
 (add) -> Monitored Short
 (add) -> Bright Object (not a short)

Snowball -> Unusual Snowballs  - rename for all instruments
Dominant MSA Leakage -> Noticeable MSA Leakage  rename for all instruments
Optical Short -> New Short  rename for all instruments
Cosmic Ray Shower - keep as is for miri, remove option from other instruments
Unusual Cosmic Rays - create this for all non miri instruments, migrate existing cosmic ray shower values here
Scattered Light - Enable for Nirspec
(add) -> Needs Discussion to all

NOTE!! @mfixstsci  and @bhilbert4 :
After releasing anomaly changes to production, Before Bringing back up the webapp,  we need to manually update the table named jwql_anomalies for:
	`Unusual Cosmic Rays` - created this for all non miri instruments, migrate existing cosmic ray shower values here
	`Scattered Light` - Migrate Nirspec existing GHOST anomalies to this column

### CODE REVIEW

**Comment by BradleySappington** [comment]
https://jira.stsci.edu/browse/JWQL-155

**Comment by BradleySappington** [comment]
@bhilbert4 and @mfixstsci  - I included a bug fix for our special case anomalies not being updated in DB.  This PR should be prioritized and released as soon as reasonably possible.  Its currently ready for review and testing

**Comment by melanieclarke** [comment]
@BradleySappington - are the changes up on a test server somewhere I can access?

**Comment by BradleySappington** [comment]
Not currently, only on my local Mesa2.
If the code review passes I will merge to test for all to look at and try to break.
I omitted the parens.  And just said “Bright Object Not A Short”.

If that’s not acceptable please let me know!

From: Melanie Clarke ***@***.***>
Reply-To: spacetelescope/jwql ***@***.***>
Date: Thursday, January 18, 2024 at 4:32 PM
To: spacetelescope/jwql ***@***.***>
Cc: Bradley Sappington ***@***.***>, Mention ***@***.***>
Subject: Re: [spacetelescope/jwql] Anomaly naming (PR #1435)


@BradleySappington<https://urldefense.com/v3/__https:/github.com/BradleySappington__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!0kR-q-WOjf9m_De5HeGjYkT6dVr2LfmsvXlke9Z8vFzuQMFK5fkbUNglaBM2joZOtrB2AkiQuecjPBEGKqygfyi1SJYG$> - are the changes up on a test server somewhere I can access?

**Review by melanieclarke — APPROVED** [review]
Everything looks good to me!  Bright Object Not A Short is clear enough.

**Review by mfixstsci — APPROVED** [review]
Thanks @BradleySappington!

**Comment by mfixstsci** [comment]
@BradleySappington, when we merge into the develop branch should we perform the same changes you listed above on the development servers database?

**Comment by BradleySappington** [comment]
> @BradleySappington, when we merge into the develop branch should we perform the same changes you listed above on the development servers database?

Development database doesn't matter too much, so no, we dont need to transition anything there

**Pull request merged**
