### PR TITLE
Add support for new python versions

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR adds support for new python versions (3.7, and hopefully 3.8).

- [x] Add new environment file for 3.7
- [x] Update Jenkins file to run tests under 3.7
- [x] Address any failing tests under 3.7
- [x] Add new environment file for 3.8
- [x] Update Jenkins file to run tests under 3.8
- [x] Address any failing tests under 3.8

### CODE REVIEW

**Comment by bourque** [comment]
Closes #526

**Comment by bhilbert4** [comment]
Jenkins is failing when it installs jsonschema 2.6 (which is quite old. 3.2 is current), and then runs into a problem when ASDF requires a more recent version. However, there is another issue which may be more important. Jenkins does not install `jwst` because: `unknown url type: git+https -- Some packages may not be found!`

**Comment by bhilbert4** [comment]
Also, pysiaf currently does not support python 3.8, which is why I was getting unsolvable conflicts for that.

**Comment by bhilbert4** [comment]
That previous commit is mostly just to restart Jenkins and see if we get the same `git+https` error

**Comment by bhilbert4** [comment]
@bourque all tests are now passing. I tweaked some versions in setup.py and requirements.txt. The `git+https` lines are still present. I'm not entirely sure why they didn't give an error this time around.

**Comment by bourque** [comment]
I tested the 3.7 env by running all of our unit tests locally.  There were some failures (e.g. #619), but they are unreleated to the environment I believe.  Will try the same for 3.8 next.

**Comment by bourque** [comment]
Alright this should be good to go pending a successful Jenkins build!

**Pull request merged**
