### PR TITLE
Bypass authentication for users running web app locally

### LINKED ISSUE #675: Bypass web app login for local developers
Currently the web app log in button only works through `localhost` for myself, and will likely stay that way based on how things are set up on the MAST side of things.  We should implement a workaround that bypasses this login when running the web app locally.

### PR DESCRIPTION
**Pull request by bourque**
This PR adds a condition in `oauth.py` which allows users running the web app locally to automatically bypass login.

Closes #675

### CODE REVIEW

**Comment by bourque** [comment]
@tnking97 Could you review this for me? and make sure that this works for you locally?

**Review by tnking97 — COMMENTED** [review]
I'm sure this will be a very helpful feature! There's a comment on part of the feature that's affecting the forms.py page.

**Comment by bourque** [comment]
Thanks for the review @tnking97!  I think I resolved the anomaly submit issue in my latest commit.  Please let me know if you find any other issues.

**Review by tnking97 — APPROVED** [review]
Yes, this solved the issue with the anomaly table! I think everything looks good.

**Pull request merged**
