### PR TITLE
Flake8 sweep

### PR DESCRIPTION
**Pull request by tnking97**
Do flake8 sweep as described in #715

### CODE REVIEW

**Review by bourque — CHANGES_REQUESTED** [review]
Thank you @tnking97 for all of this!  This PR might go down in the history of the project as having the most changes 😅 .  We had strayed further from our style guide/PEP8 than I had thought.

I noticed some lingering `flake8` issues that still exist within the repository.  To find these, I used:

```
cd jwql/jwql/  # navigate to the top of the package (not the top of the repository)
flake8 . --ignore E501,E402,E722,F811,W503,F401 --exclude *data_trending*
```

Note that I've ignored a few flags that we probably don't need to care too much about (e.g. line too long) and i'm ignoring the `data_trending` modules for now, since those modules need to still be refactored (#547).  I see that you already made some changes to the `data_trending` modules, which is fine and will only help us in the future, so thank you for that!

You've made a ton of changes already, so I would be happy to take care of these if you'd like, just let me know.

**Comment by tnking97** [comment]
Hi @bourque, thank you for the review! I didn't realize that you could check flake8 suggestions in that way, so thank you very much for the tip! I have made a few more changes, but there are a small number of suggestions that I am not certain we should adhere to. A few items are much more readable as they are (eg, change hanging indent suggestions), a few comparison suggestions that are optional function parameters I believe should be kept as '==' rather than 'is', a few undefined or unused variables seem to have a purpose in one way or another (eg, if else statements), and a few error seem to be examples. Perhaps I'm not quite understanding a handful of these correctly, so please do let me know if you have other thoughts or changes to request.

Here are the items that are left:
./style_guide/typing_demo/typing_demo_1.py:33:81: E231 missing whitespace after ':'
./style_guide/typing_demo/typing_demo_1.py:64:1: F722 syntax error in forward annotation "hey i'm metadata!"
./style_guide/typing_demo/typing_demo_3.py:60:1: F821 undefined name 'reveal_type'
./style_guide/typing_demo/typing_demo_2.py:66:16: F821 undefined name 'x'
./jwql/instrument_monitors/common_monitors/dark_monitor.py:445:31: E127 continuation line over-indented for visual indent
./jwql/instrument_monitors/common_monitors/dark_monitor.py:445:67: E712 comparison to True should be 'if cond is True:' or 'if cond:'
./jwql/instrument_monitors/common_monitors/readnoise_monitor.py:382:13: E128 continuation line under-indented for visual indent
./jwql/instrument_monitors/common_monitors/readnoise_monitor.py:382:42: E712 comparison to True should be 'if cond is True:' or 'if cond:'
./jwql/instrument_monitors/common_monitors/bias_monitor.py:288:13: E123 closing bracket does not match indentation of opening bracket's line
./jwql/instrument_monitors/common_monitors/bias_monitor.py:297:46: E712 comparison to True should be 'if cond is True:' or 'if cond:'
./jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py:689:31: E127 continuation line over-indented for visual indent
./jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py:689:48: E712 comparison to True should be 'if cond is True:' or 'if cond:'
./jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py:872:29: F821 undefined name 'new_badpix_file'
./jwql/instrument_monitors/common_monitors/bad_pixel_monitor.py:873:22: F821 undefined name 'badpix_mask'
./jwql/website/apps/jwql/bokeh_dashboard.py:179:13: E123 closing bracket does not match indentation of opening bracket's line
./jwql/website/apps/jwql/bokeh_dashboard.py:187:13: E123 closing bracket does not match indentation of opening bracket's line
./jwql/website/apps/jwql/monitor_pages/monitor_bias_bokeh.py:71:13: F841 local variable 'dummy_instrument' is assigned to but never used
./jwql/website/apps/jwql/monitor_pages/monitor_bias_bokeh.py:72:13: F841 local variable 'dummy_aperture' is assigned to but never used
./jwql/website/apps/jwql/monitor_pages/monitor_dark_bokeh.py:95:13: F841 local variable 'dummy_instrument' is assigned to but never used
./jwql/website/apps/jwql/monitor_pages/monitor_dark_bokeh.py:96:13: F841 local variable 'dummy_aperture' is assigned to but never used
./jwql/website/apps/jwql/monitor_pages/monitor_readnoise_bokeh.py:71:13: F841 local variable 'dummy_instrument' is assigned to but never used
./jwql/website/apps/jwql/monitor_pages/monitor_readnoise_bokeh.py:72:13: F841 local variable 'dummy_aperture' is assigned to but never used
./jwql/website/apps/jwql/monitor_pages/monitor_bad_pixel_bokeh.py:176:13: F841 local variable 'dummy_instrument' is assigned to but never used
./jwql/website/apps/jwql/monitor_pages/monitor_bad_pixel_bokeh.py:177:13: F841 local variable 'dummy_aperture' is assigned to but never used
./jwql/website/apps/jwql/monitor_pages/monitor_bad_pixel_bokeh.py:233:17: F841 local variable 'real_data' is assigned to but never used
./jwql/jwql_monitors/monitor_filesystem.py:329:33: E126 continuation line over-indented for hanging indent
./jwql/jwql_monitors/monitor_filesystem.py:453:33: E226 missing whitespace around arithmetic operator
./jwql/jwql_monitors/generate_preview_images.py:614:117: W291 trailing whitespace
./jwql/tests/test_database_interface.py:79:83: W504 line break after binary operator
./jwql/tests/test_database_interface.py:80:83: W504 line break after binary operator
./jwql/utils/constants.py:321:21: E126 continuation line over-indented for hanging indent
./jwql/utils/monitor_template.py:141:5: F841 local variable 'result_of_second_function' is assigned to but never used
./jwql/utils/utils.py:204:12: F821 undefined name 'httplib'

**Comment by bourque** [comment]
@tnking97 Yes, totally agree, and you raise excellent points/examples.  As you have probably seen, PEP8 mentions that it makes sense to ignore PEP8 in favor of readability and understanding of the code and its intentions, and I think the examples that you mention fall in this realm, so no need to make changes on those.

I will re-review this early next week and resolve the lingering merge conflicts, and this should be good to go!  Thank you!

**Review by bourque — APPROVED** [review]
Thank you @tnking97 for the updates on this! This looks good to merge!

**Pull request merged**
