### PR TITLE
fix ignore of original and stream suffixes for generate_preview_images

### LINKED ISSUE #944: Preview images/thumbnails for "stream" files
It looks like we are still creating preview images/thumbnails for "stream" files (e.g. jw01163148001_gs-fg_2022090163856_stream.fits). Right now the code is creating a preview image for every 100th integration in an exposure. But the stream files can have tens of thousands of integrations, so we're still ending up with a huge number of preview images for each. This is filling up directories and disk space, and greatly slows the preview image generator.

We should either completely turn off the preview image generation for these files, or perhaps just create them for a handful of extensions, if the FGS team decides they'd want to see them. @shanosborne any thoughts on that?

### PR DESCRIPTION
**Pull request by BradleySappington**
properly ignore "original" and "Stream" when getting filenames in generate_preview_images

### CODE REVIEW

**Review by bhilbert4 — APPROVED** [review]
Good catch! This looks good to me.

**Review by mfixstsci — APPROVED** [review]
Hey @BradleySappington just went ahead and tested this real quick and it works just fine. Thank submitting this.

**Comment by mfixstsci** [comment]
Just merged #942 which includes some fixes for the tests. Assuming the tests pass, this should be good to go!

**Comment by mfixstsci** [comment]
@BradleySappington and @bhilbert4 looks like the changes solved our time out issue 🎉 @BradleySappington is this ready to go?

**Pull request merged**
