### PR TITLE
Add info on bug/feature requests to about page

### PR DESCRIPTION
**Pull request by bsunnquist**
This PR makes changes to the about page to describe the bug/feature request instructions for users.

### CODE REVIEW

**Comment by bsunnquist** [comment]
@bourque we had some info in our contact section already for this, so I just added a little more details to it instead of making a new section. But let me know if you were wanting more detailed instructions, e.g. like this: https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-repository

**Comment by bourque** [comment]
Closes #788

**Comment by bourque** [comment]
@bsunnquist These changes look great!

But now that I think about this some more, it would probably also be good to have something on our homepage, as users may not think to go over to the About page for this.  Could you add a little button towards the bottom of the homepage that directs users to https://github.com/spacetelescope/jwql/issues/new/choose?  Maybe something like:

```
Found a bug or have a feature request?

<Submit an issue>
```

**Comment by bsunnquist** [comment]
Yeah that's a good idea - I just submitted that change

**Review by bourque — APPROVED** [review]
@bsunnquist Awesome, this looks perfect!  Thanks again!

**Pull request merged**
