### PR TITLE
Reformat query page functionality

### LINKED ISSUE #1178: Make the query page fully functional
Update the query page such that users can filter and search for data using various observation/exposure properties. 

As part of this, move more information about exposures into the Django models, in order to make filtering easier.

- [x] #1184
- [x] #1185
- [x] #1186
- [x] #1187
- [x] #1188
- [x] #1189
- [x] #1190
- [x] #1191

### LINKED ISSUE #1184: Update constants in filters with up-to-date values (filters, gratings, etc)

### LINKED ISSUE #1188: verify all thumbnails are returned on query

### LINKED ISSUE #1189: Have Info filled for thumbnails hover

### LINKED ISSUE #1190: Clear checks on navigate "back" OR show checked fields.

### LINKED ISSUE #1191: Clear form button

### PR DESCRIPTION
**Pull request by BradleySappington**
Reformat how the query page works to access using the django model DB

### CODE REVIEW

**Comment by BradleySappington** [comment]
Ready for Review and loaded on Dev

**Review by melanieclarke — APPROVED** [review]
I think this is good to go.  The new query functionality seems to be working great on the backend - it's finding the right files, and returning within a reasonable amount of time, even with broad queries that return many results.  The clear form button is much appreciated too!

There are a couple things that aren't quite working on the front end yet, but they are bigger in scope than this PR and should be addressed separately.

One, there are occasional errors in the navigate_filter function, affecting file/exposure grouping.  This is probably related to issue https://github.com/spacetelescope/jwql/issues/1201.

Two, large queries throw "insufficient resources" errors when trying to load all thumbnails in the query results page.  This seems to happen for around 2000 thumbnails or more.  For very broad queries (e.g. nircam + nrcalong, ~14000 results), the page eventually errors out completely.  This should probably be addressed in the front end by adding pagination for large result sets.  This is likely to have site-wide design consequences and should be studied separately.

**Review by mfixstsci — APPROVED** [review]
Changes look great @BradleySappington. I would still like to test them but once I do that, I will merge. Thanks for working on this and for your patience in my review. Thank you @melanieclarke for reviewing as well!

**Comment by mfixstsci** [comment]
@BradleySappington just got back to testing the changes today. Sorry for the delay. Merging!

**Pull request merged**
