### PR TITLE
Algorithm documentation

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR adds some documentation to the instrument monitors describing the algorithms used. Documentation for the bad pixel monitor has been added to the docstring for the module, so that it will show up in the API documentation on readthedocs.

### CODE REVIEW

**Comment by bhilbert4** [comment]
@bourque I've added documentation for the bad pixel monitor. For the dark monitor, details of what the monitor is doing are spread throughout the comments in the code itself. If people are interested in seeing that written out, I could pull comments from the code and place them in a new page somewhere. I imagine the same is true for the bias and readnoise monitors. @bsunnquist

**Comment by bourque** [comment]
Thank you for adding this @bhilbert4!  Is this still a WIP or is it ready for review?

At this point in time, I am satisfied with just making sure our docstrings are well-detailed in regards to the algorithms (as you have done here for the bad pixel monitor).  Perhaps at some point we can consolidate all of the algorithm descriptions in a single document or a single area (e.g. the About page on the web app) if the instrument teams would be interested in that, but we can cross that bridge when we come to it.

**Comment by bhilbert4** [comment]
If there are no other algorithm descriptions that were requested by the teams, or that are missing, then I consider this ready to merge. Looking at what is currently in the API documentation pages on RTD, I think things look reasonably complete. I'm just not sure if there are any outstanding specific requests from the instrument teams that didn't show up in Francesca's notes from the demos.

**Comment by bourque** [comment]
@bhilbert4 Perfect, thanks.  I'll check this against Francesca's notes before merging.

**Comment by bourque** [comment]
There were not other particular requests from the teams about algorithm descriptions, so I think this is good to go.  Thanks again @bhilbert4!

**Review by bourque — APPROVED** [review]

**Pull request merged**
