### PR TITLE
NIRCam Background Monitor updates

### PR DESCRIPTION
**Pull request by bsunnquist**
This PR makes the following changes based on NIRCam team feedback:

- Incorporates the JWST background tool (JBT) predictions into the NIRCam Background Monitor (requires `pip install jwst_backgrounds` in jwql environment). This also requires two new columns in the NIRCamClawStats database (`doy` and `total_bkg`).
- Plots 3 types of trending plots on the Background Monitor page, that you can tab between (see screenshot below): background levels, background rms, and background/model.
- Expanded segmentation maps before calculating image statistics, mainly to allow for better rms calculations that aren't impacted by fainter source wings.

Screen Shot 2024-01-23 at 10 47 08 AM

### CODE REVIEW

**Comment by bhilbert4** [comment]
Could you add JBT to the environment files, requirements.txt, and (I think) setup.py?

**Comment by bsunnquist** [comment]
Added the JBT to the requirements - looks like the regression tests all ran OK. Most packages required by `jwst_backgrounds` were already in our jwql environment, with the exception of `healpy`.

**Comment by mfixstsci** [comment]
Thanks for this @bsunnquist looks like we have a conflict. Would you mind resolving it? Thank you!

**Comment by bsunnquist** [comment]
@mfixstsci merge conflict should be fixed now

**Comment by mfixstsci** [comment]
> @mfixstsci merge conflict should be fixed now

Thank you @bhilbert4 I will go ahead and review!

**Review by mfixstsci — APPROVED** [review]
Thank you @bsunnquist this looks great. I am going to test it locally as well.

**Comment by mfixstsci** [comment]
Just finished local testing, thank you @bsunnquist everything looks good to me 👍

**Comment by bsunnquist** [comment]
Thanks @mfixstsci ! Did you get those 2 new database columns working on the server (doy and total_bkg)? If so, I'll prepare a request to insert some historical data into those updated databases in a separate issue.

**Comment by mfixstsci** [comment]
As of right now, I don't believe the columns are there but the web application and figure generation were successful. We are meeting today to discuss the database changes!

**Pull request merged**
