### PR TITLE
Pass base context through context processor

### LINKED ISSUE #273: Find better way to pass context to base HTML template
Currently, our `base.html` template requires some data to be passed to it, such as:

```python
context = {'inst': '',
           'inst_list': JWST_INSTRUMENT_NAMES,
           'tools': MONITORS,
            'user': user}
```

This means the each view defined in `views.py` requires this context to be gathered and passed.  This is a bit annoying and not very DRY.  Perhaps there is a more elegant solution.

### PR DESCRIPTION
**Pull request by bourque**
This PR adds `context_processor.py` and contains corresponding changes in `views.py` and `settings.py` to allow for the passing of `context` needed by the `base.html` template to occur in one function, instead of defining the same `context` in each view.

Closes #273

### CODE REVIEW

**Comment by bourque** [comment]
@laurenmarietta Sorry to keep pouring on the review requests 😅

**Comment by laurenmarietta** [comment]
(I see that #322 will restrict access further, I just thought that there was already a requirement to log into any page with the `auth_info` decorator...)

**Comment by bourque** [comment]
@laurenmarietta This behavior is expected; we had set up the log in button and various authentication-related views to authenticate a user, but we hadn't restricted any part of the web app based off of that yet, so basically it has been a meaningless button.  But yes, indeed #322 will introduce some restricted areas of the web app, in anticipation of #294.

**Comment by bourque** [comment]
@laurenmarietta You may be thinking of the period of time in which some of the views were broken because we were not passing the `user` information to them?  I think that was the case at some point in time, though my memory is also hazy.

**Pull request merged**
