### PR TITLE
Make bias monitor tests

### PR DESCRIPTION
**Pull request by bsunnquist**
Adds unit tests for the bias monitor

### CODE REVIEW

**Comment by mfixstsci** [comment]
Hey @bsunnquist, all of the tests run just fine. I do have a question about `test_extract_zeroth_group`. Why are we interested in saving the `zeroth` data extension of and then reading it back in for comparison? Is this something that is temporary? Checking a bug in the pipeline? Besides that, the other tests are straight forward and look good!

**Review by mfixstsci — APPROVED** [review]
Everything looks good!

**Comment by bsunnquist** [comment]
Thanks @mfixstsci ! The Bias Monitor is just concerned with the 0th group, so I have it create a new file of just that group to save memory space and pipeline processing time (the NIRCam calibration darks we'll get are very large, 100+ groups) - so that test is just to make sure that function creates this new file properly.

@bourque this is ready to be merged.

**Comment by mfixstsci** [comment]
@bsunnquist ahhhh got it. I was missing the instrument specific knowledge on this one :sweat_smile: Makes much more sense now! Thanks!

**Comment by bourque** [comment]
Thanks @bsunnquist and @mfixstsci!  @bsunnquist could you just add the appropriate sphinx API docs to this PR?  Then we should be good to go.

**Comment by bsunnquist** [comment]
@bourque I added this to the `tests.rst` file and it looked ok locally. Let me know if there are other steps involved though (never done spinx before).

**Comment by bourque** [comment]
@bsunnquist Thanks, thats perfect!

**Pull request merged**
