### PR TITLE
Make readnoise tests

### PR DESCRIPTION
**Pull request by bsunnquist**
Added tests for the readnoise monitor

### CODE REVIEW

**Comment by bourque** [comment]
This might be the first time I've ever seen @pep8speaks come back with no issues!  Congrats!

**Comment by bsunnquist** [comment]
Thanks @mfixstsci! Yes I believe that's the case, since jenkins can't access central storage to get the files needed for those tests (I copied that strategy from `test_dark_monitor.py`).

**Comment by mfixstsci** [comment]
Thanks @bsunnquist, just wanted to double check. Might be a better question for @bourque but, do we plan on adding these files to `Jenkins` in the future? Or do we have a regression testing suite set up?

**Comment by bourque** [comment]
@mfixstsci @bsunnquist  Yeah, we do have plans to spin up an internal Jenkins server that would have access to central storage and thus be able to run all of those tests (https://github.com/spacetelescope/jwql/issues/504), but it is not yet implemented, so for now we just ignore those tests in the current Jenkins build.

**Comment by mfixstsci** [comment]
@bourque sounds good. When we are ready to set that infrastructure up, I would be willing to help since I've done a fair bit of it for the JWST Pipeline unit/regression testing suite. Besides that @bsunnquist everything else looks good!

**Pull request merged**
