### PR TITLE
Fix missing reffile error handling in Readnoise Monitor

### PR DESCRIPTION
**Pull request by bsunnquist**
This PR fixes the error handling in the Readnoise Monitor when no matching CRDS reffile can be found.

### CODE REVIEW

**Comment by bourque** [comment]
Ideally this will close #762 if no further issues are found during testing of this PR.

**Comment by bourque** [comment]
@bsunnquist It looks like another error came up when testing on the DMS data:

```
07/26/2021 15:45:13 PM INFO: 	Readnoise image saved to /outputs/dev/readnoise_monitor/data/nirspec_nrs_s1600a1_slit/jw00626045001_02101_00001_nrs1_uncal_refpix_readnoise.fits
07/26/2021 15:45:13 PM INFO: 	Readnoise image stats: 0.14629 +/- 0.00077
07/26/2021 15:45:13 PM INFO: 	Readnoise image stats by amp: {'amp1_mean': 0.14628678914552523, 'amp1_stddev': 0.000772924353007172, 'amp1_n': array([    0,     0,     0,     2,     0,     0,     0,     0,  6135,
           0,     1,     4,     1,     1,     1,     1,     0,     0,
           0, 25428,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0]), 'amp1_bin_centers': array([0.14328343, 0.14346009, 0.14363676, 0.14381343, 0.1439901 ,
       0.14416677, 0.14434344, 0.1445201 , 0.14469677, 0.14487344,
       0.14505011, 0.14522678, 0.14540345, 0.14558012, 0.14575678,
       0.14593345, 0.14611012, 0.14628679, 0.14646346, 0.14664013,
       0.14681679, 0.14699346, 0.14717013, 0.1473468 , 0.14752347,
       0.14770014, 0.1478768 , 0.14805347, 0.14823014, 0.14840681,
       0.14858348, 0.14876015, 0.14893682, 0.14911348, 0.14929015])}
07/26/2021 15:45:13 PM INFO: 	Pipeline readnoise reffile is /grp/crds/cache/references/jwst/jwst_nirspec_readnoise_0036.fits
07/26/2021 15:45:13 PM CRITICAL: Traceback (most recent call last):
  File "/jwql/utils/logging_functions.py", line 284, in wrapped
    func(*args, **kwargs)
  File "l/jwql/jwql/utils/logging_functions.py", line 249, in wrapped
    func(*args, **kwargs)
  File "readnoise_monitor.py", line 593, in run
    self.process(new_files)
  File "readnoise_monitor.py", line 460, in process
    readnoise_diff = readnoise - pipeline_readnoise
ValueError: operands could not be broadcast together with shapes (32,1024) (0,1024) 

07/26/2021 15:45:13 PM CRITICAL: CRASHED

```

Do you know what is going on here?

**Comment by bsunnquist** [comment]
Looks like some generic reffiles can sometimes be cutouts of the full-frames themselves, so in this case I need to make a cutout of a cutout. I just submitted a change that should fix this.

While I was doing this, I also realized some older files might have incorrect substrt values that have since been changed in pysiaf (e.g. nircam coro darks, potentially) - since this would also crash this cutout step, I also made it robust to this scenario.

I think all of the bases are covered now, but if it gets too complicated I can always just run the readnoise on fullframes only (the subarray tracking is a "nice to have" at the moment anyway).

**Review by bourque — APPROVED** [review]
Thanks @bsunnquist, this looks great, and testing this with the latest DMS build now completes successfully!

**Pull request merged**
