### PR TITLE
Allow more guide star attempts in filename parser

### LINKED ISSUE #1004: File does not match filename conventions
In the latest run of generate_preview_images, the filename parser crashed with:

ValueError: Provided file jw01141001001_gs-id_12_stacked_uncal.fits does not follow JWST naming conventions.

The filename parser is being used to identify guide star observations, which are then skipped by geneerate_preview_images.

### PR DESCRIPTION
**Pull request by bhilbert4**
Resolves #1004 

This PR tweaks the allowed filename format for guide star observations such that the number of guide star ID attempts can now be up to 999. Previously this was only a single digit, and the code crashed when it encountered a file with 12 attempts. I think in reality the number of attempts will never go much higher than that, but I figured it couldn't hurt to go to triple digits.

### CODE REVIEW

**Comment by bhilbert4** [comment]
@mfixstsci or @BradleySappington, do one of you have a couple minutes to review this? This issue caused generate_preview_images to crash on the ops server last night. I'd like to get this in and restart that job.

**Comment by BradleySappington** [comment]
on it

**Review by BradleySappington — COMMENTED** [review]
consider creating
FILE_GUIDESTAR_ATTMPT_LEN_MIN=1
FILE_GUIDESTAR_ATTMPT_LEN_MAX=3
or since you just explained it to me and its only used in one place currently, adding the explanation comment to that line of code to explain the magic number

**Comment by bhilbert4** [comment]
All set. I updated the constants. I also added a couple tests.

**Review by BradleySappington — APPROVED** [review]
looks great!

**Pull request merged**
