### PR TITLE
Add step_args to calwebb_detector1_save_jump

### PR DESCRIPTION
**Pull request by bhilbert4**
This missing step_args keyword is just an oversight from the work done in #1262

### CODE REVIEW

**Comment by bhilbert4** [comment]
Would be good to test this on the dev/test server

**Comment by bhilbert4** [comment]
This one is looking good. A test I ran over the weekend completed successfully. I pulled this branch onto the test server this afternoon. The crontab will run the bad pixel monitor at 6pm as a final test. I would kick it off manually now, but there are other monitors running at the moment.

**Comment by bhilbert4** [comment]
Test run completed successfully.
@mfixstsci this is ready for review.

**Review by mfixstsci — APPROVED** [review]
LGTM! Sorry for the delay @bhilbert4!

**Pull request merged**
