### PR TITLE
Prepare models for external postgres db

### PR DESCRIPTION
**Pull request by BradleySappington**
Common changes for postgres django models DB (transfer from sqlite to postgres)

### CODE REVIEW

**Comment by BradleySappington** [comment]
ITSD had to create new databases.
Postgres DBs have to be updated to version 11 or greater in order to work with Django Models.
ITSD updating all jwql dbs to be version 14

**Review by mfixstsci — APPROVED** [review]
Straightforward here. Going to approve while DBs are being upgraded this afternoon.

**Comment by BradleySappington** [comment]
@mfixstsci , this is still WIP.  I need to still transfer the models to the new Postgres DB.  May need more changes, but will let you know. Not ready for merge.

**Comment by BradleySappington** [comment]
In order to migrate database successfully the following must be read BEFORE merging to production (at this point in time, DEV)

Step 01: Dump production sqlite db to json (BEFORE MERGE)
        bring down jwql and stop all cronjobs that update the db.  Make sure no processes are running.
	python manage.py dumpdata --indent 4 > data.json
        (you will need to manually update the beginning few entries to make sure that "FIELDS" isn't empty and `instrument = INS_NAME` is populated.
	
Step 02a: Merge to production
Step 02b: manually update config.json to account for new fields merged in from example_config.json

Step 03: Create tables without migration
	python3 manage.py migrate --run-syncdb

Step 04: Open django shell. Then exclude contentype data

	python3 manage.py shell
	from django.contrib.contenttypes.models import ContentType
	ContentType.objects.all().delete()
	quit()

Step 05: Load Data
	python3 manage.py loaddata data.json

Step 06: Verify in postgres that data is loaded
Step 07: Bring up JWQL and verify working properly.

**Pull request merged**
