### PR TITLE
[WIP] Bias monitor bokeh plots

### LINKED ISSUE #538: Specify Bias Monitor plots
We need to use the bokeh templating language to build up the plots for the bias monitor.

### PR DESCRIPTION
**Pull request by bourque**
This PR adds monitor plots to the web app for the bias monitor.  Closes #538.

### CODE REVIEW

**Comment by bourque** [comment]
@bsunnquist FYI, the files that need to be edited are:

- `jwql/website/apps/jwql/monitor_pages/yaml/bias_monitor_interface.yaml` - YAML file for bokeh templating language.  Defines which plots are constructed and what bokeh objects they contain.
- `jwql/website/apps/jwql/monitor_pages/monitor_bias_bokeh.py`: This file will contain code to load data from the database and assign any data needed to bokeh plot objects.  It also defines the layout of the plot objects.

**Comment by bourque** [comment]
Here is a mock up for these plots per @bsunnquist :

Screen Shot 2020-03-25 at 10 15 53 AM

**Comment by bourque** [comment]
Hey @bsunnquist if you are ever looking for something to do, feel free to take over this PR, especially now that you have some good bokeh templating expertise 😉 .  But definitely no pressure, I will get to it at some point regardless.

**Comment by bsunnquist** [comment]
sounds good! Yeah, I think it will be pretty straightforward now after the readnoise plots; I could do it for the next release if you wanted

**Comment by bourque** [comment]
Thank you @bsunnquist for solving this in #680.  This PR is now redundant and can be closed.

**Pull request closed without merging**
