### PR TITLE
dark_monitor for all instruments

### LINKED ISSUE #374: Instrument-specific dark monitor updates
#229 adds the Dark Current Monitor to JWQL. The scope of the added functionality in that PR is to get the dark current monitor working for NIRCam. Some additional tweaks will be necessary in order to make the code functional for all of the other instruments. 

The purpose of this issue is to gather together the edits needed for the other instruments.

Known updates needed so far:

### MIRI Amplifier Definitions
The amplifiers on MIRI read out pixels in a different pattern than in any of the other instruments. For the other instruments, each amplifier reads out a contiguous block of pixels (e.g. from (x,y) = (0,0) to (511, 2047)). But in MIRI the amplifiers read out interleaved columns (double check that it is columns rather than rows) of pixels. (i.e. Columns 0 - 7 are read out by: amp1, amp2, amp3, amp4, amp1, amp2, amp3, amp4).

The amplifier definitions currently in the `amplifier_info` function cannot handle this pattern at the moment. It should be updated to do so, or possibly fall back to a situation where we say that all pixels are read out by a single amplifier. Could be interesting to pull apart and monitor the pixels from each amp separately, even though they are interleaved.

### MIRI Subarrays
All MIRI subarrays are read out using all 4 amplifiers. This affects the frame time calculation. Be sure this information is not needed elsewhere.

### MIRI Frametime Calculation
@mwregan2 sent me a notebook with a function that calculates the MIRI frame time for a given aperture. This needs to be added to the frame time calculation function.

### NIRSpec Amplifier Definitions
Request sent to @cherylpavlovsky asking about which pixels are read out by which amplifiers

### NIRSpec Frametime Calculation
Request sent to @cherylpavlovsky asking about frame time calculation.

### NIRSpec Subarrays
Request sent to @cherylpavlovsky asking about number of amplifiers used to read out various subarrays

### NIRISS Subarrays
All NIRISS subarrays are read out using a single amplifier, except for four: WFSS64C, WFSS64R, WFSS128C, and WFSS128R. The latter two should be added to `FOUR_AMP_SUBARRAYS` in `utils/constants.py`. The first two are already present there.

### PR DESCRIPTION
**Pull request by bourque**
This PR makes appropriate changes to the `dark_monitor` to get it working for all JWST instruments. 

Closes #374

### CODE REVIEW

**Comment by laurenmarietta** [comment]
Something to include here: `test_amplifier_info` is failing for me locally because of the `DQ` keyword problem that was discussed in #229 - it doesn't seem to exist for the `test_image_ff.fits` image.

This hasn't been failing on Jenkins because that test is skipped (since you would have to go on central storage to get the image).

**Comment by bhilbert4** [comment]
I also fixed the `PIXELDQ` to `DQ` fits file extension error mentioned by @laurenmarietta above.

**Comment by bhilbert4** [comment]
Running the updated code one instrument at a time shows that there are no MIRI darks at all in the filesystem, and only 3 or 4 NIRISS darks, meaning that we can't really test these instruments. NIRSpec apparently does have enough darks for the `NRS1_FULL` aperture, but the `dark_monitor` crashes because (at least) one of the filenames returned by the MAST query does not exist in the filesystem.

**Comment by cracraft** [comment]
I'll work on getting some MIRI darks into the system for testing.

**Comment by bourque** [comment]
@bhilbert4 Could you share an example of a filename that exists in MAST but not in our filesystem?  I would like to follow through with the archive folks and find out where we are going astray.

**Comment by bhilbert4** [comment]
FileNotFoundError: jw96216009001_02101_00004_nrs1_dark.fits is not in the predicted location: /grp/jwst/ins/jwql/filesystem/jw96216/jw96216009001_02101_00004_nrs1_dark.fits

**Comment by cracraft** [comment]
Quick question, where is this reading the data from? I can put a few files into the filesystem, but is that where the code is looking? Is this doing a MAST query to a different location? Also, does it look for APERNAME as the keyword in the file to know what aperture to read in from the thresholds table? Create_data currently lists the apername as #todo, so that's something I have to edit myself before putting the data anywhere.

**Comment by bhilbert4** [comment]
Yes, the code is looking in the filesystem as defined in the config.json file. The MAST query is looking into MAST, so there is an assumption made that the filesystem contains everything that is in MAST. And APERNAME is important. The dark monitor loops over all possible apertures as defined in pysiaf and searches for darks taken with that aperture.

**Comment by cracraft** [comment]
So if I prepare some darks for testing, just putting them into the filesystem is enough? I don't need to try to get them put into MAST as well?

**Comment by bourque** [comment]
@cracraft Note that you could also create your own directory for testing, and then just point the `filesystem` key in your `config.json` file to said directory.  As long as the files in that directory are organized like the actual filesystem (e.g. `/home/some_dir/jw12345/jw12345...uncal.fits`), I think it should work.

**Comment by bhilbert4** [comment]
But the files do need to be in MAST, otherwise the query won't find them...
If the files aren't in MAST, then for testing you could comment out the mast query and just provide a list of your test files.

**Comment by cracraft** [comment]
I pulled the version of dark_monitor.py in bhilbert4/dark-monitor-inst-specifics and was able to get it to run successfully (success message in log) without making any changes. As soon as I commented out the MAST query in line 258 and substituted in a dictionary of MIRI files, I got a crash in the code. Can someone take a look at the log (in the usual directory) dark_monitor_2019-06-26-13-08.log and help me figure out what's going on? It's still convinced it has NIRCam files. All files listed in the successful run were NIRCam, and this still assumes NIRCam as the default. Did I grab the right version of the code?

**Comment by bhilbert4** [comment]
It looks like the dark_monitor is still looping over instruments. See line 704. What if you change that such that it only works on MIRI?

**Comment by cracraft** [comment]
This is why I'm asking if I have the right version of the code. Here's what I see for lines 704/705.
       # signal-to-noise
        aperture_type = Siaf(self.instrument)[self.aperture].AperType

**Comment by bhilbert4** [comment]
Hmmm yeah. There's something strange going on there. I see that statement on line 575.

**Comment by cracraft** [comment]
Ok, I downloaded the version in bourque/dark-monitor-all-instruments instead, and think I finally have the right version of the code. However, I was unable to get it to finish running, either without making changes, or when I tried to give it a list of MIRI darks.

If I didn't change anything in the code and just attempted to run it, I get the results in dark_monitor_2019-06-26-15-28.log: 
06/26/2019 15:29:55 PM INFO: Working on aperture NRCA1_FULL in nircam
06/26/2019 15:29:55 PM INFO: 	No query history for NRCA1_FULL. Beginning search date will be set to 57357.0.
06/26/2019 15:29:55 PM INFO: 	Query times: 57357.0 58660.81130880348
06/26/2019 15:29:55 PM INFO: 	Aperture: NRCA1_FULL, new entries: 22
06/26/2019 15:29:55 PM INFO: 	Sufficient new dark files found for nircam, NRCA1_FULL to run the dark monitor.
06/26/2019 15:29:55 PM CRITICAL: Traceback (most recent call last):
  File "/ifs/jwst/wit/miri/cracraft/jwqldev/jwql/jwql/utils/logging_functions.py", line 279, in wrapped
    func(*args, **kwargs)
  File "/ifs/jwst/wit/miri/cracraft/jwqldev/jwql/jwql/utils/logging_functions.py", line 244, in wrapped
    func(*args, **kwargs)
  File "dark_monitor.py", line 739, in run
    new_filenames = [filesystem_path(file_entry['filename']) for file_entry in new_entries]
  File "dark_monitor.py", line 739, in <listcomp>
    new_filenames = [filesystem_path(file_entry['filename']) for file_entry in new_entries]
  File "/ifs/jwst/wit/miri/cracraft/jwqldev/jwql/jwql/utils/utils.py", line 348, in filesystem_path
    raise FileNotFoundError(('{} is not in the predicted location: {}'.format(filename, full_path)))
FileNotFoundError: jw00759101001_02101_00001_nrca1_dark.fits is not in the predicted location: /grp/jwst/ins/jwql/filesystem/jw00759/jw00759101001_02101_00001_nrca1_dark.fits

06/26/2019 15:29:55 PM CRITICAL: CRASHED

And if, instead, I try to substitute line 728 (new_entries = mast_query_darks(instrument, aperture, self.query_start, self.query_end)) with a dictionary of MIRI files instead, I get the following from log dark_monitor_2019-06-26-15-44.log. The code is assuming the MIRI files are whatever the original first file found was (FGS in this case), and so just changing out the new_entries listing doesn't seem an appropriate way to test this.

06/26/2019 15:46:30 PM INFO: 	Running pipeline on /ifs/jwst/wit/miri/cracraft/jwqldev/outtest/dark_monitor/data/fgs_fgs1_full_oss/jw04191001001_01101_00001_mirimage_uncal.fits
06/26/2019 15:46:30 PM INFO: DQInitStep instance created.
06/26/2019 15:46:30 PM INFO: Step DQInitStep running with args ('/ifs/jwst/wit/miri/cracraft/jwqldev/outtest/dark_monitor/data/fgs_fgs1_full_oss/jw04191001001_01101_00001_mirimage_uncal.fits',).
06/26/2019 15:46:30 PM ERROR: Can't open input
06/26/2019 15:46:30 PM CRITICAL: Traceback (most recent call last):
  File "/ifs/jwst/wit/miri/cracraft/jwqldev/jwql/jwql/utils/logging_functions.py", line 279, in wrapped
    func(*args, **kwargs)
  File "/ifs/jwst/wit/miri/cracraft/jwqldev/jwql/jwql/utils/logging_functions.py", line 244, in wrapped
    func(*args, **kwargs)
  File "dark_monitor.py", line 763, in run
    self.process(dark_files)
  File "dark_monitor.py", line 541, in process
    processed_file = pipeline_tools.run_calwebb_detector1_steps(os.path.abspath(filename), steps_to_run)
  File "/ifs/jwst/wit/miri/cracraft/jwqldev/jwql/jwql/instrument_monitors/pipeline_tools.py", line 211, in run_calwebb_detector1_steps
    model = PIPELINE_STEP_MAPPING[step_name].call(input_file)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/jwst-0.13.1-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 532, in call
    return instance.run(*args)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/jwst-0.13.1-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/jwst-0.13.1-py3.6-macosx-10.7-x86_64.egg/jwst/dq_init/dq_init_step.py", line 40, in process
    input_model = datamodels.RampModel(input)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/jwst-0.13.1-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/ramp.py", line 38, in __init__
    super(RampModel, self).__init__(init=init, **kwargs)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/jwst-0.13.1-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/model_base.py", line 103, in __init__
    asdf_file = AsdfFile()
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/asdf/asdf.py", line 122, in __init__
    self._process_extensions(extensions)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/asdf/asdf.py", line 206, in _process_extensions
    self._extensions = default_extensions.extension_list
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/asdf/extension.py", line 233, in extension_list
    self._extension_list = AsdfExtensionList(self.extensions)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/asdf/extension.py", line 226, in extensions
    self._load_installed_extensions()
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/asdf/extension.py", line 197, in _load_installed_extensions
    ext = entry_point.load()
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jsonschema 3.0.1 (/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages), Requirement.parse('jsonschema<=2.6,>=2.3'), {'asdf'})

06/26/2019 15:46:30 PM CRITICAL: CRASHED


Either way, it's not running for me.

**Comment by bhilbert4** [comment]
Hmm. I'm not sure what's going on with the nircam files not working. But in the case with the dictionary of MIRI files, did you also change the instrument loop such that it's only going over MIRI?

**Comment by cracraft** [comment]
I did make that change, and am still seeing odd behavior. It still tries to use the first aperture in the list of MIRI files found in the filesystem, which is MIRIM_FULL_OSS, when the actual file list I give the script is MIRIM_FULL. But the main problem is that is sees there are no rate files and tries to run the pipeline, but claims not to be able to open the file. I have tested two of the files through detector1 to be sure, and the pipeline has no problem with the files, so it's not that the pipeline can't open the files. 
Here's that trace:
06/27/2019 09:54:41 AM INFO: 	Running pipeline on /ifs/jwst/wit/miri/cracraft/jwqldev/outtest/dark_monitor/data/miri_mirim_full_oss/jw04191001001_01101_00001_mirimage_uncal.fits
06/27/2019 09:54:41 AM INFO: DQInitStep instance created.
06/27/2019 09:54:41 AM INFO: Step DQInitStep running with args ('/ifs/jwst/wit/miri/cracraft/jwqldev/outtest/dark_monitor/data/miri_mirim_full_oss/jw04191001001_01101_00001_mirimage_uncal.fits',).
06/27/2019 09:54:41 AM ERROR: Can't open input
06/27/2019 09:54:41 AM CRITICAL: Traceback (most recent call last):
  File "/ifs/jwst/wit/miri/cracraft/jwqldev/jwql/jwql/utils/logging_functions.py", line 279, in wrapped
    func(*args, **kwargs)
  File "/ifs/jwst/wit/miri/cracraft/jwqldev/jwql/jwql/utils/logging_functions.py", line 244, in wrapped
    func(*args, **kwargs)
  File "dark_monitor.py", line 763, in run
    self.process(dark_files)
  File "dark_monitor.py", line 541, in process
    processed_file = pipeline_tools.run_calwebb_detector1_steps(os.path.abspath(filename), steps_to_run)
  File "/ifs/jwst/wit/miri/cracraft/jwqldev/jwql/jwql/instrument_monitors/pipeline_tools.py", line 211, in run_calwebb_detector1_steps
    model = PIPELINE_STEP_MAPPING[step_name].call(input_file)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/jwst-0.13.1-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 532, in call
    return instance.run(*args)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/jwst-0.13.1-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/jwst-0.13.1-py3.6-macosx-10.7-x86_64.egg/jwst/dq_init/dq_init_step.py", line 40, in process
    input_model = datamodels.RampModel(input)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/jwst-0.13.1-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/ramp.py", line 38, in __init__
    super(RampModel, self).__init__(init=init, **kwargs)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/jwst-0.13.1-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/model_base.py", line 103, in __init__
    asdf_file = AsdfFile()
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/asdf/asdf.py", line 122, in __init__
    self._process_extensions(extensions)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/asdf/asdf.py", line 206, in _process_extensions
    self._extensions = default_extensions.extension_list
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/asdf/extension.py", line 233, in extension_list
    self._extension_list = AsdfExtensionList(self.extensions)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/asdf/extension.py", line 226, in extensions
    self._load_installed_extensions()
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/asdf/extension.py", line 197, in _load_installed_extensions
    ext = entry_point.load()
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jsonschema 3.0.1 (/Users/cracraft/anaconda3/envs/jwql/lib/python3.6/site-packages), Requirement.parse('jsonschema<=2.6,>=2.3'), {'asdf'})

06/27/2019 09:54:41 AM CRITICAL: CRASHED

**Comment by bhilbert4** [comment]
The monitor loops over all possible apertures when looking for files. It generates the loop of possible apertures using pysiaf. Look for "possible_apertures" in the code. So you'll need to restrict possible_apertures to be only MIRIM_FULL.

I saw a traceback similar to that, with a version conflict in a package related to the pipeline,  in Mirage yesterday. That one was ultimately caused by me using python 3.7 in my environment. Pulling back to 3.6 solved the issue.

**Comment by bhilbert4** [comment]
I just tried running the dark monitor and ran into the same problem @cracraft mentioned earlier, where a NIRCam file that was found in the MAST query is not in the filesystem. The file in question is from proposal 759, which was part of the WFR2 rehearsal. So it seems like these data have just recently been added to MAST? I thought they'd be in the SID archive or some special branch of MAST.

**Comment by cracraft** [comment]
I have edited the code so that it only looks for MIRIM_FULL to match my data, make sure it only iterates on MIRI data and only has my set of 10 MIRI files. I am also using a python 3.6.4 environment. It still crashes with the same asdf error in the logs and this printed to the command line:
2019-06-27 10:27:00,070 - stpipe.DQInitStep - ERROR - Can't open input
Traceback (most recent call last):
  File "dark_monitor.py", line 1008, in <module>
    update_monitor_table(module, start_time, log_file)
  File "/jwql/utils/utils.py", line 443, in update_monitor_table
    new_entry['status'] = get_log_status(log_file)
NameError: name 'get_log_status' is not defined

Any ideas?

**Comment by bhilbert4** [comment]
@cracraft, did you ever get the dark monitor to work? Looking at the error you posted above, it looks like you are looking at an old version of the code. `update_monitor_table` is now in `monitor_utils.py`, rather than `utils.py`.

If you have the MIRI darks somewhere, I could try running the dark monitor using those.

**Comment by cracraft** [comment]
I thought you were already able to run the code with MIRI darks, which is why I haven't put more effort into getting it running on my computer.

**Comment by bhilbert4** [comment]
I had forgotten that there are MIRI darks in the filesystem. I just tried again and the calculations completed successfully on the MIRIM_FULL data. @bourque is there any other testing/work we should do on this before reviewing/merging (other than returning the dark monitor to looping over all instruments and resolving the conflicts)?

**Comment by bourque** [comment]
@bhilbert4 I can't think of anything else at the moment! Please proceed, and I can give it one final test in the test environment before we merge.

**Comment by bhilbert4** [comment]
Ok @bourque, conflicts resolved, and it should be looping over all instruments and apertures now.

**Comment by bourque** [comment]
The code changes look good to me.  I am now testing this branch on the test server and will merge if it completes successfully

**Comment by bourque** [comment]
This appears to be completing successfully now, so I am going to merge this!

**Pull request merged**
