### PR TITLE
Fix failing MIRI dark montior

### LINKED ISSUE #1062: Standardize the lists and order of the instrument monitors in the pull-down menu
Right now the monitors listed in the instrument pull-downs are ordered randomly (and the CR monitor appears twice in MIRI's list). 
It might be nice to go with alphabetical order for these, just so that things are consistent from instrument-to-instrument. Of course, lists will diverge as we add monitors that are specific to only some instruments, but it seems like it'd be nice to have a predictable order to the entries.

### LINKED ISSUE #1130: MIRI dark monitor is crashing
MIR dark monitor page is crashing with:

unsupported operand type(s) for -: 'list' and 'list'

http://localhost/miri/dark_monitor/
3.1.7
TypeError
unsupported operand type(s) for -: 'list' and 'list'
website/apps/jwql/monitor_pages/monitor_dark_bokeh.py, line 142, in pre_init

### PR DESCRIPTION
**Pull request by bhilbert4**
Small change to the bokeh templating code for the dark monitor to assure that data retrieved from the DB is a numpy array. The array is needed in order to do element-wise subtraction later.

I also removed 2 unnecessary list comprehensions. Much easier to get the array directly rather than looping over database rows.

### CODE REVIEW

**Comment by bhilbert4** [comment]
The dark monitors now appear to be loading reliably. I also took a couple minutes to re-order the list of monitors in the instrument drop downs so that they are in alphabetical order. I also removed the cosmic ray monitor links since that's turned off for everyone.

**Comment by bhilbert4** [comment]
@mfixstsci this is ready for review.

**Review by mfixstsci — APPROVED** [review]
Thanks! Looks good to me. Straight forward changes. Do you think we should remove the commented out code instead of leaving it in there?

**Comment by bhilbert4** [comment]
Do you mean the empty links? We probably could remove those. My impression is that the CR monitor is coming back soon, so maybe we keep that one in there.

**Comment by bhilbert4** [comment]
Ok, all set. I checked it on the test server and it looks good.

**Comment by mfixstsci** [comment]
@bhilbert4 should we rebase and merge this? Or do we need to hold off for another PR?

**Comment by bhilbert4** [comment]
I can't think of any reason why we'd need to wait for anything else.

**Pull request merged**
