### PR TITLE
Turn off thumbnail creation for all but rate files

### LINKED ISSUE #957: Creation of unnecessary thumbnails
The only thumbnails used by the web app are a single representative thumbnail, which is used on the Archive page, and the thumbnail for the SCI extension for each exposure, used on the program page. 

But our thumbnail generation code currently creates thumbnails for every filetype associated with each exposure (e.g. uncal, rate, cal). This is leading to the creation of lots of thumbnails that are never actually used. We should restrict the thumbnail generation code to create only one thumbnail for each exposure. I think using the rate file is probably the best choice, since some observations never go through later stages of the pipeline and will never have e.g. cal.fits versions made, or for modes like WFSS, the stage 2 output contains cutouts of each source. I *think* all files go through stage1 and produce rate files though.

### PR DESCRIPTION
**Pull request by bhilbert4**
Resolves #957 

This PR makes changes to the preview image generation code such that thumbnail images are created only for rate files. Currently we are creating thumbnail files for all file types (uncal, rate, cal, etc). However, we only need one thumbnail for each file, since the instrument archive pages do not show separate images for each file type.

### CODE REVIEW

**Comment by bhilbert4** [comment]
- [x] Make sure the pages that show thumbnails for a given proposal are only looking for thumbnail files from rate images
- [x] Test on dev or test server
- [x] Dark current observations don't produce rate files. They have uncal.fits and dark.fits. Adjust code to work for one of these filetypes, just for dark observations.

**Comment by bhilbert4** [comment]
Interested to hear what @BradleySappington thinks of these changes, since he's spent a lot of time recently looking at preview/thumbnail image generation.

**Comment by BradleySappington** [comment]
This looks good with the understanding that the dark files will not be created until the third task is completed.

**Review by BradleySappington — APPROVED** [review]
Looks good, would hold off on merge until dark code is included.

**Comment by bhilbert4** [comment]
First test on the dev server failed due to a typo in the filename to save the thumbnails to. Typo has been fixed in the latest commit, and this is ready for re-testing on the dev server. Concentrate on program 1062, whose thumbnails I removed.

**Comment by bhilbert4** [comment]
Tested on the test server. The code successfully made thumbnail files only for rate and dark files, as expected. I then tested and these new thumbnail images were successfully displayed on pages for individual programs.

@mfixstsci I think this is ready for review. Once this is in, I think we'll be in good shape to regenerate thumbnails on the ops server.

**Comment by bhilbert4** [comment]
Ah sorry, I forgot that @BradleySappington reviewed this earlier. Either one or both of you are welcome to check the latest updates.

**Comment by mfixstsci** [comment]
@BradleySappington would you like to do the honors and merge it?

**Review by BradleySappington — APPROVED** [review]

**Comment by BradleySappington** [comment]
yessir!

**Comment by bhilbert4** [comment]
Thanks!

**Comment by BradleySappington** [comment]
@mfixstsci I currently lack authorization to merge

**Comment by mfixstsci** [comment]
That's okay @BradleySappington, the branch was stale so we had to merge all of our recent updates into this branch. Once the tests pass, send it.

**Comment by BradleySappington** [comment]
Tests passed, but merging is blocked because I'm not authorized.  This is a "protected branch"

**Comment by BradleySappington** [comment]
Screen Shot 2022-07-22 at 1 14 32 PM

**Pull request merged**
