### PR TITLE
Fix API view for filenames per proposal and preview images

### LINKED ISSUE #1044: API page for preview images is crashing
https://jwql-test.stsci.edu/api/1068/preview_images/

- [x] Crashes with an error that it's trying to call split() on a tuple.

### LINKED ISSUE #1047: Update tests that rely on central store/data access
Many of our tests rely on having access to a copy of the filesystem. These tests are skipped by default when running GitHub Actions. We've missed that we need to update these tests to reflect the real data in the filesystem now. The tests currently reference various simulated datasets that are no longer visible in MAST. 

See e.g. test_data_containers.py

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR fixes a small bug in the API view for retrieving a list of filenames for a given proposal.

### CODE REVIEW

**Comment by bhilbert4** [comment]
@mfixstsci I think I've fixed these issues. I think we should remove the API view that shows all preview image filenames for an instrument (and same with the list of thumbnails per instrument). These lists are already long enough that they are creating bad gateway errors. With these views removed, a user could still build up a list of all files by looping over proposals for a given instrument and getting the preview images for each proposal.

Do you agree? Or maybe we should keep the options but comment them out for now, and hope that the bad gateway errors will be resolved independently?

**Comment by bhilbert4** [comment]
All tests in data_containers are now passing, including those that are skipped on Github.

**Review by mfixstsci — APPROVED** [review]
Hey @bhilbert4 thanks for submitting this. Everything looks good to me.

I am okay with removing the API links but I would also like to update the API page with an example of looping through the propsals to get the filenames.

**Comment by bhilbert4** [comment]
Current status: API documentation and view have been cleaned up such that they are all working and reference in-flight data. Checking the views in the browser show that everything looks good. So from that standpoint, this is ready for review. However, programmatic access is failing because the requests all return the SSO page.

**Comment by mfixstsci** [comment]
> Current status: API documentation and view have been cleaned up such that they are all working and reference in-flight data. Checking the views in the browser show that everything looks good. So from that standpoint, this is ready for review. However, programmatic access is failing because the requests all return the SSO page.

Thanks @bhilbert4 I am rebasing the branch now. I submitted a ticket to IT for them see if there is a way to bypass the SSO page.

**Comment by bhilbert4** [comment]
@mfixstsci conflicts are resolved and the unrelated test failures have resolved themselves. I think this is ready to go.

**Comment by bhilbert4** [comment]
@fix, assuming the latest test pass, are you ok with merging this? The changes to the tests that are in this PR should fix the failures seen in the filesystem monitor PR.

**Review by mfixstsci — APPROVED** [review]
@bhilbert4 everything looks straight forward here. Thank you for contributing and thank you for writing tests.

**Pull request merged**
