### PR TITLE
Add max length to charfield

### PR DESCRIPTION
**Pull request by BradleySappington**
Define Constants and add Django max_length parameter to CharField

### CODE REVIEW

**Review by bhilbert4 — APPROVED** [review]
Looks good to me. I was a little nervous about the aperture length, but I checked in pysiaf and the longest aperture name I've found is only 28 characters, so it seems like we're all good there.

**Comment by BradleySappington** [comment]
@bhilbert4, would you like me to increase anyway?  a lot of the numbers are arbitrary

**Comment by bhilbert4** [comment]
@BradleySappington I think it's ok as is. Should we be worried about anyone who creates a filename that's longer than 100 characters?

**Comment by BradleySappington** [comment]
@bhilbert4, 100 was the previous value so I kept it.  Happy to increase if you think its important?

**Comment by BradleySappington** [comment]
@bhilbert4 , scratch that, It's arbitrary, I'll bump it up to 150

**Review by mfixstsci — APPROVED** [review]
LGTM

**Comment by BradleySappington** [comment]
bumping up to 1k since most filenames use full path

**Pull request merged**
