### PR TITLE
Update About page with new developers

### LINKED ISSUE #988: Update the About page
Our list of contributors on the About page needs to be updated. In addition to removing those no longer on the team, we also need to add @BradleySappington and @penaguerrero

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR updates the About page to show the current developers. Previously, the developers were shown in a single png that created from individual images that were stitched together. This update changes that so that separate images are used, which should make future updates much easier.

Resolves #988

### CODE REVIEW

**Comment by bhilbert4** [comment]
- [x] Still need to figure out how to work in names beneath the images. Maybe have full names be part of the image filenames. We can extract from there. Then just need to add them below each image using caption, as is done here: https://www.w3schools.com/bootstrap/bootstrap_images.asp

Reverted to manual html for the photos. I was spending too much time trying to get it automated.

**Comment by bhilbert4** [comment]
Looks good. @mfixstsci this is ready for review.

**Comment by bhilbert4** [comment]
Checked on the test server. Looks good.

**Review by mfixstsci — APPROVED** [review]
Man, I really wish I wore a different shirt that day when I got my picture taken. Thanks for the updates 😅

**Pull request merged**
