### PR TITLE
Reorganize repository

### PR DESCRIPTION
**Pull request by bourque**
This PR reorganizes the `jwql` repository structure to better allow for instrument-specific monitors to be incorporated.

### CODE REVIEW

**Comment by bourque** [comment]
@bhilbert4 I didn't really know who to ask to review this, so I'm choosing you randomly.  Could you take a look for any obvious mistakes?

**Comment by bourque** [comment]
Closes #125

**Comment by bhilbert4** [comment]
Where should we put monitor scripts that apply to >1 instrument? In `instrument_monitors` along side the subdirectories for each instrument? My expectation is that there will be at least some monitors that use methods that everyone agrees on and will therefore be run on multiple instruments.

**Comment by bourque** [comment]
@bhilbert4 Sorry, I forgot to add a `common_monitors/` directory as I had described in #125.  I've added it now.  Do you think that is the best landed spot for such modules?

**Comment by bhilbert4** [comment]
Yeah, I think that makes sense.

**Pull request merged**
