### PR TITLE
Fix test_utils

### PR DESCRIPTION
**Pull request by bsunnquist**
This fixes https://github.com/spacetelescope/jwql/issues/625.

The problem was one of the files in our filesystem (jw04192001001_01101_00001_MIRIMAGE_uncal.fits) had an uppercase detector name. I made a simple edit to `utils.py` to make it robust to this when searching for the matching instrument.

### CODE REVIEW

**Comment by bsunnquist** [comment]
@bourque There is also this random hidden file the causes test_utils to fail:
`/grp/jwst/ins/jwql/filesystem/jw04192/._jw04192001001_01101_00001_MIRIMAGE_uncal.fits`

I was going to remove it, but figured I'd check with you first in case it was important.

**Comment by cracraft** [comment]
As the creator of the file (using a script written in SCSB to convert ground test data to pipeline format), I can't see any need for a hidden version of the file. I assume it's the same as the non-hidden version. But since I haven't developed code, also good to check with Matt.

**Comment by bourque** [comment]
@bsunnquist @cracraft Yeah I agree, we should be fine to remove this!

**Comment by bourque** [comment]
Alright I went ahead and removed that file.  I am also going to redact the filepath from the comments for security purposes.

**Review by bourque — APPROVED** [review]
Thanks @bsunnquist!

**Pull request merged**
