### PR TITLE
[WIP] Reformatting via black

### LINKED ISSUE #160: Consider using Black?
Black is the "uncompromising Python code formatter": https://github.com/ambv/black 

It is certainly uncompromising, so might not be best for our project, but a lot of people here at DjangoCon are really into it for enforcing consistent programming across a project. Something to consider!

### PR DESCRIPTION
**Pull request by bourque**
This PR makes formatting changes to the software within the repository via `black`.

Closes #160

### CODE REVIEW

**Comment by laurenmarietta** [comment]
Information on Black's GitHub about how to include it in a pre-commit hook: https://github.com/ambv/black#version-control-integration

**Comment by bourque** [comment]
@spacetelescope/jwql As I mentioned at our last meeting, please take a look at this PR and let me know (by commenting on this PR) if you have any strong opinions on this one way or the other.

**Comment by cracraft** [comment]
I can see how parts of Black would make it easier to find argument parameters, but aesthetically, I don't really like the formatting.

**Comment by laurenmarietta** [comment]
I'm partial to it, if only for the work I think it could save us when reviewing PRs. It would be nice to not have to worry about how many blank lines, line length, indentation, quotes, etc., and just be able to focus on the content.

(That said, the formatting does look a bit silly in places 😬)

**Comment by bourque** [comment]
We have decided to punt on this for now.  We will leave #160 open but close this PR.

**Pull request closed without merging**
