### PR TITLE
Update 'data_dir' to 'working_data_dir' for dark monitor

### LINKED ISSUE #1459: Dark monitor attempts to use nonexistent "data_dir" attribute
**Describe the bug**
When the configuration key dictionary was updated to include both a "working" and an "output" directory, all monitors were updated to use the appropriate directory. In the dark monitor, on line 1014 (and again about a dozen lines later), the "data_dir" attribute was not updated to "working_data_dir", and as a result an exception is raised, because there is no longer a "data_dir" attribute.

**To Reproduce**
1. Run the dark monitor
2. See error

**Expected behavior**
The dark monitor should run without errors.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by york-stsci**
This fixes a bug in the dark monitor where, in two places, data_dir was not updated to working_data_dir.

### CODE REVIEW

**Comment by york-stsci** [comment]
I'm sorry, I accidentally did this as a branch in the main repository rather than as a branch in my fork. Hopefully that won't cause any problems.

**Review by bhilbert4 — APPROVED** [review]
Looks good to me. Just a couple of instances where the data_dir -> working_data_dir were missed previously?

**Comment by york-stsci** [comment]
Correct. I think this one is mercifully easy and ready to go.

**Review by mfixstsci — COMMENTED** [review]
LGTM

**Pull request merged**
