### PR TITLE
MIRI Data Trending

### PR DESCRIPTION
**Pull request by DanielKuebi**
Development of a dashboard for data-trending of MIRI.

### CODE REVIEW

**Comment by DanielKuebi** [comment]
**What it´s for**
For MIRI and seemingly also for other instrument teams it is important to see how certain parameters trend over time (years). Therefore we query a 15min sample once a day for specific mnemonics and grap out data under certain conditions. All values of each mnemonic that apply to a given condition are used to calculate an average and a deviation for this sample. -> This data is then stored in a seperate auxilary database. 
Since there are also parameters that are just provided rarely (wheel movements etc.) we also take a sample representing the whole day, process it and store it in the database. 

**What it does**
At the moment there are two seperate scripts to process the data for 15min and whole-day samples. 
By running the script the software imports data from a CSV sheet, sorts it by each mnemonic identifier and appends it to a dictionary `("mnemonic_identifier" : Astropy Table)`. This reduced AstropyTable just holds the time and the engineering value in seperate columns. Functions provided in `condition.py` and `process_data.py` apply certain conditions and extract useful data. This useful data will be used to calculate mean and deviation. 
By opening the corresponding web page a function in `views.py` calls `dasboard.py` which generates a bokeh figure holding all predefined plots on seperate tabs.

**How it works**
There is no data from actual tests availlable in the EDB. Therfore I prepared a prefilled database that can be used and queried by the implemented dashboard. `/databases/miri_database.db`
To setup a new database walk through following steps: 

1. go to `/utils` folder and run `python sql_interface.py` -> this will generate a new empty database with tables for all mnemonics listed in `mnemonics.py`. This could cause trouble when the prepared database with the same name is still in the database folder

2. `Download trainigs data from https://drive.google.com/open?id=1SERCSDNgYM4B and https://drive.google.com/open?id=1Cu_js_zEepzGO0ufr1SIBOR3fqx4fbJM and put it to a appropriate place 

3. point `directory = ` in 15_min_to_db.py und day_to_db.py to the folder where the trainigsdata was saved and run both scripts. These will process the data provided in the .CSV files. 

4. enjoy

**Comment by Johannes-Sahlmann** [comment]
@DanielKuebi the first drive.google link seems broken.

**Comment by Johannes-Sahlmann** [comment]
@bourque can you please place the training dataset in the appropriate place on central storage?

**Comment by DanielKuebi** [comment]
@Johannes-Sahlmann this should work 
https://drive.google.com/open?id=1SERCSDNgYM4BbNIbzqAL3IUKwLEGejsB

**Comment by bourque** [comment]
@Johannes-Sahlmann I have copied the files over to central store.  For security purposes, I will send you the location via Slack.

**Comment by Johannes-Sahlmann** [comment]
Is this ready for me to try it out locally? 
Has anyone else (except @DanielKuebi ) already done that?

**Comment by bourque** [comment]
I haven't tried that yet.  Hoping to get to it tomorrow, unless you want to do it @Johannes-Sahlmann

**Comment by laurenmarietta** [comment]
Due to a few conflicts, this PR is now replaced by #326. Let's have any additional discussion there.

**Pull request closed without merging**
