### PR TITLE
Add more info to image- and exposure-level pages

### LINKED ISSUE #1304: Add more descriptive information to the image and exposure pages
Currently, the image and exposure pages have very minimal descriptive information for the file(s) shown: only proposal, observation, visit, and detector (for image pages).

It would be helpful to include some more high-level description for context: the exposure type, proposal category, filter/grating, etc.  Essentially, any field that appears in filtering or sorting elsewhere in the application would be nice to have on the image pages.

### PR DESCRIPTION
**Pull request by bhilbert4**
Resolves #1304 

Add more information about the current exposure to the image-level and exposure-level pages. In order to try and save space, much of this information is placed in a collapsible text box.

### CODE REVIEW

**Comment by bhilbert4** [comment]
@mfixstsci this is ready for review.

**Comment by bhilbert4** [comment]
@BradleySappington if you're inspired, feel free to give a quick look-over. My css and js updates seem to be doing what I want (after our meeting on Friday), but there was a fair amount of bumbling around to arrive at what works. If you're not inspired though, no problem.

**Review by BradleySappington — COMMENTED** [review]
LGTM!

**Review by BradleySappington — APPROVED** [review]

**Review by mfixstsci — APPROVED** [review]
Hey @bhilbert4 this all looks good. Thanks for your work on this. I remember seeing it in action last week on our huddle. Glad we are able to get this in.

**Comment by mfixstsci** [comment]
@bhilbert4 if you could just resolve the conflict in `test_data_containers.py` we can merge this in.

**Comment by bhilbert4** [comment]
> @bhilbert4 if you could just resolve the conflict in `test_data_containers.py` we can merge this in.

Done!

**Pull request merged**
