### PR TITLE
Release-driven git workflow

### LINKED ISSUE #295: Adopt release-driven git workflow
Currently we are using a git workflow wherein feature branches are merged into `spacetelescope:master` via pull requests.  However, if we want to be more careful about how we deploy our services to a production server (#294), we will only want to deploy to production when a release happens.  Thus, it would be beneficial to merge pull requests into a separate `release-vx.y.z` branch, and then only merge the `release-vx.y.z` branch into `master` when completely satisfied.  Here is a graphical representation of what I am thinking:

git-release-workflow

### PR DESCRIPTION
**Pull request by bourque**
This PR updates our documentation to describe a new release-driven git workflow for the `jwql` project.  Updated documents include:

- `README.md`
- `style_guide.md`
- The wiki for [`git`/GitHub workflow](https://github.com/spacetelescope/jwql/wiki/git-&-GitHub-workflow-for-contributing)
- The wiki for [software releases](https://github.com/spacetelescope/jwql/wiki/Software-Releases)
- The wiki for [Checklist for Contributors and Reviewers of PRs](https://github.com/spacetelescope/jwql/wiki/Checklist-for-Contributors-and-Reviewers-of-Pull-Requests)

Closes #295

### CODE REVIEW

**Comment by bourque** [comment]
@Johannes-Sahlmann Could you review this?  It would be good to have someone with the perspective of a frequent contributor take a look at this to make sure it all makes sense.

**Comment by laurenmarietta** [comment]
RE: the software releases wiki page: should we add a final step that merges the `release-x.y.z` branch back into the `develop` branch? I realized when looking at the helpful diagram you added in the workflow wiki that we'l need to merge it or else we won't have the commit with the new version number and updates to `CHANGES.rst` in `develop`.

Also, should we considering adding a note somewhere about the workflow for hot-fixes? Since those also require merging into first `master` and then `develop`?

**Comment by bourque** [comment]
@laurenmarietta Ah yes, good ideas.  I will make the appropriate updates (and also make a PR into `develop` for our latest release just now)

**Comment by Johannes-Sahlmann** [comment]
Yes. I will review.

**Comment by bourque** [comment]
I added some text to the software releases and git/GitHub workflow wiki to include @laurenmarietta's suggestions.

**Comment by bourque** [comment]
@Johannes-Sahlmann Thanks for the comments, they are all good.  I've made changes based on your suggestions, let me know what you think!

**Pull request merged**
